spring.application.name=student-api

# ===============================
# MYSQL
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/student_api?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=pasword

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================

server.port=8080

# ===============================
# 2GIS
# ===============================

2gis.api-key=c2e26b5c-7a1f-4245-b270-9ff1767e0e66